name: bft_clientes
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  sliding_up_panel: ^2.0.0+1
  shimmer: ^3.0.0
  get: ^4.6.6
  firebase_core: ^2.30.0
  mask_text_input_formatter: ^2.9.0
  cloud_firestore: ^4.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: SupermercadoOne
      fonts:
        - asset: assets/fonts/SupermercadoOne-Regular.ttf

    - family: TenorSans
      fonts:
        - asset: assets/fonts/TenorSans-Regular.ttf

    - family: Akatab
      fonts:
        - asset: assets/fonts/Akatab-Regular.ttf
        - asset: assets/fonts/Akatab-Medium.ttf
          weight: 500
        - asset: assets/fonts/Akatab-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Akatab-Bold.ttf
          weight: 700
        - asset: assets/fonts/Akatab-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Akatab-Black.ttf
          weight: 900

    - family: Harmattan
      fonts:
        - asset: assets/fonts/Harmattan-Regular.ttf
        - asset: assets/fonts/Harmattan-Medium.ttf
          weight: 500
        - asset: assets/fonts/Harmattan-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Harmattan-Bold.ttf
          weight: 700
