// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjZd13unIOwIMOvCylT_oVjgHiebU-XTw',
    appId: '1:428365924437:web:9c4611baba7c8f18096cdc',
    messagingSenderId: '428365924437',
    projectId: 'flt-barber',
    authDomain: 'flt-barber.firebaseapp.com',
    storageBucket: 'flt-barber.appspot.com',
    measurementId: 'G-WHK5FJXTMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIV37PcK48O3sTRk_j76a7nBpkvjewjgE',
    appId: '1:428365924437:android:008e1fee9b759f0e096cdc',
    messagingSenderId: '428365924437',
    projectId: 'flt-barber',
    storageBucket: 'flt-barber.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCISxPpbsz4FMlh1hIBA-fwztdDMVzUrvM',
    appId: '1:428365924437:ios:97eda25cee07a186096cdc',
    messagingSenderId: '428365924437',
    projectId: 'flt-barber',
    storageBucket: 'flt-barber.appspot.com',
    iosBundleId: 'com.bllqt.bftClientes',
  );

}